### ISSUE TITLE
Some link doesn't work

### ISSUE THREAD

**Issue by xcv58** [blue-systems-group/project.phonelab.doc#1]
For example, in https://phone-lab.org/doc/existing.html

```
Action: android.location.LOCATION_CHANGED
Project: frameworks/base
File: services/java/com/android/server/LocationManagerService.java:1978
Description: Location update.
```

The link for `services/java/com/android/server/LocationManagerService.java:1978` is:
http://platform.phone-lab.org:8080/gitweb?p=platform/frameworks/base.git;a=blob;f=services/java/com/android/server/LocationManagerService.java;hb=refs/heads/phonelab/android-4.4.4_r1/develop#l1978

But it return `Not Found`

**Comment by jhshi** [comment]
As noted above in that page, you'll need to login in another tab first to make these links work. Somehow gitweb will not prompt login.

**Comment by xcv58** [comment]
I already sign in, and it doesn't work.

**Comment by jhshi** [comment]
Oh, then it's probably Gerrit permission issue. I think I just fixed it, can you try again?

**Comment by xcv58** [comment]
Yes, I think it's fixed.
